services:
  dagster-webserver:
    build: .
    working_dir: /app
    user: "0:0"
    env_file:
      - .env                    # load all env vars for dbt/meltano/dagster
    environment:
      DAGSTER_HOME: /app/orchestration/dagster_home
      PYTHONPATH: /app/orchestration
    volumes:
      - .:/app
      - ./.keys:/app/.keys
    ports:
      - "3000:3000"
    command: >
      dagster-webserver
      -h 0.0.0.0
      -p 3000
      -w workplace.yaml
    restart: unless-stopped

  dagster-daemon:
    build: .
    working_dir: /app
    user: "0:0"
    env_file:
      - .env
    environment:
      DAGSTER_HOME: /app/orchestration/dagster_home
      PYTHONPATH: /app/orchestration
    volumes:
      - .:/app
#      - ${GCP_KEY_PATH_HOST}:/app/.keys
      - ./.keys:/app/.keys
    depends_on:
      - dagster-webserver
    command: >
      dagster-daemon run -w workplace.yaml
    restart: unless-stopped
